name: healthmate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  path: ^1.8.3
  provider: ^6.1.1
  intl: ^0.20.2
  flutter_svg: ^2.0.7
  curved_navigation_bar: ^1.0.3
  percent_indicator: ^4.2.2
  pdf: ^3.10.6
  printing: ^5.11.2
  share_plus: ^12.0.1
  path_provider: ^2.1.3
  google_fonts: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  